version: "3.9"
services:
  redis:
    image: redis
    volumes:
    - ./data:/data
  counter:
    build: .
    ports:
      - 80:3000
    environment:
      - PORT=3001
      - REDIS_URL=redis://redis
    depends_on:
      - redis